openapi: 3.0.0
info:
  description: "API"
  version: "1.0.0"
  title: "API"
paths:
  /api/v1/products/{id}:
    get:
      summary: "Get an information about the product"
      description: ""
      operationId: "GetProduct"
      security:
        - bearerAuth: []
      parameters:
        - in: "path"
          name: "id"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Expected response to a valid request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
